name: Build Executable

on:
  push:
    branches:
      - "*RC*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Change this to the Python version you are using
    # - run: pip install -r requirements.txt pyinstaller

    - name: Extraire les numéros de version
      id: extract-versions
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "Branche : $BRANCH_NAME"
        
        if [[ $BRANCH_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            IFS='.' read -ra VERSION_PARTS <<< "$BRANCH_NAME"
            MAJOR_VERSION=${VERSION_PARTS[0]}
            MINOR_VERSION=${VERSION_PARTS[1]}
            PATCH_VERSION=${VERSION_PARTS[2]}
            echo "Numéros de version détectés : $MAJOR_VERSION, $MINOR_VERSION, $PATCH_VERSION"
        else
            echo "La branche ne suit pas le format de version attendu."
            exit 1
        fi
        