name: Build Executable
on:
  push:
    branches:
      - "*RC*"

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        shell: pwsh
        run: |
          $RELEASE_VERSION = $env:GITHUB_REF
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $env:GITHUB_ENV
    
      - name: Extract Version
        run: |
          $versionRegex = '^.*?(\d+\.\d+\.\d+).*$'
          $matches = $env:RELEASE_VERSION -match $versionRegex

          if ($matches) {
            $extractedVersion = $matches[1]
            echo "::set-env name=EXTRACTED_VERSION::$extractedVersion"
          } else {
            echo "Version not found in the branch name."
          }

      - name: Test
        run: |
          echo "Extracted Version: ${{ env.EXTRACTED_VERSION }}"
