name: Build Executable

on:
  push:
    branches:
      - "*RC*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Change this to the Python version you are using
    # - run: pip install -r requirements.txt pyinstaller

    - name: Extraire les numéros de version
      id: extract-versions
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}

        if [ "$(echo $BRANCH_NAME | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$')" ]; then
            MAJOR_VERSION=$(echo $BRANCH_NAME | cut -d '.' -f 1)
            MINOR_VERSION=$(echo $BRANCH_NAME | cut -d '.' -f 2)
            PATCH_VERSION=$(echo $BRANCH_NAME | cut -d '.' -f 3)
            echo "Branche : $BRANCH_NAME"
            echo "Numéros de version détectés : $MAJOR_VERSION, $MINOR_VERSION, $PATCH_VERSION"
        else
            echo "La branche ne suit pas le format de version attendu."
            exit 1
        fi
