name: Build Executable
on:
  push:
    branches:
      - "*RC*"

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Change this to the Python version you are using
      - run: pip install -r requirements.txt


      - name: Set env
        shell: pwsh
        run: |
          $RELEASE_VERSION = $env:GITHUB_REF
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $env:GITHUB_ENV
    
      - name: Extract Version
        id: extract_version
        run: |
          $versionRegex = '^.*?(\d+\.\d+\.\d+).*$'

          if ($env:RELEASE_VERSION -match $versionRegex) {
            $extractedVersion = $matches[1]
            echo "EXTRACTED_VERSION=$extractedVersion" >> $env:GITHUB_ENV
          } else {
            echo "EXTRACTED_VERSION=000000000000" >> $env:GITHUB_ENV
          }

      - name: Test
        run: |
          echo "Extracted Version: ${{ env.EXTRACTED_VERSION }}"

      - name: Build
        run: pyinstaller action.spec

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OfficeAssistant
          path: dist/OfficeAssistant V${{ env.EXTRACTED_VERSION }}.exe  # Replace with the actual name used in pyinstaller.spec
